export enum Permission {

    ADD_EXERCISE = 'ADD_EXERCISE',

    MODIFY_EXERCISE = 'MODIFY_EXERCISE',

    DELETE_EXERCISE = 'DELETE_EXERCISE',

    ADD_WOD = 'ADD_WOD',

    MODIFY_WOD = 'MODIFY_WOD',

    DELETE_WOD = 'DELETE_WOD',

}